openapi: 3.1.0
info:
  title: Room Booker API
  version: 1.0.0
  description: API for booking meeting rooms

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /auth/login:
    post:
      summary: Login with password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /auth/oidc/start:
    get:
      summary: Start OIDC login
      responses:
        "302":
          description: Redirect to OIDC provider

  /auth/oidc/callback:
    get:
      summary: OIDC callback
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Callback successful

  /me:
    get:
      summary: Get current user
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /rooms:
    get:
      summary: Get rooms
      security:
        - bearerAuth: []
      parameters:
        - name: floor
          in: query
          schema:
            type: string
        - name: capacity
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: List of rooms
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Room"

  /rooms/{id}/calendar:
    get:
      summary: Get room calendar
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: from
          in: query
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: Calendar events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Event"

  /rooms/{id}/bookings:
    post:
      summary: Create booking
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookingRequest"
      responses:
        "201":
          description: Booking created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"

  /bookings/{id}:
    get:
      summary: Get booking
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Booking data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
    patch:
      summary: Update booking
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookingUpdate"
      responses:
        "200":
          description: Booking updated
    delete:
      summary: Delete booking
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Booking deleted

  /availability:
    get:
      summary: Get availability
      security:
        - bearerAuth: []
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: capacity
          in: query
          schema:
            type: integer
        - name: equipment
          in: query
          schema:
            type: string
        - name: floor
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Available slots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Availability"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        role:
          type: string
        timezone:
          type: string

    Room:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        capacity:
          type: integer
        equipment:
          type: object
        floor:
          type: string

    Event:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time

    BookingRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        participants:
          type: array
          items:
            type: string

    Booking:
      type: object
      properties:
        id:
          type: string
        room_id:
          type: string
        title:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
        status:
          type: string

    BookingUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string

    Availability:
      type: object
      properties:
        room_id:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time
